import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { FileText, Users, Database, ShieldCheck, Brain, Clock, CreditCard, LogOut, AlertTriangle, RefreshCw, Mail, Scale, BookOpen } from 'lucide-react';

const sections = [
  {
    icon: FileText,
    title: '1. Acceptance of Terms',
    content:
      'By accessing or using the Resurrectio platform, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you may not use the platform. Resurrectio is operated by CROS LLC ("we," "us," or "our"). These terms constitute a legally binding agreement between you and CROS LLC.',
  },
  {
    icon: BookOpen,
    title: '2. Description of Service',
    content:
      'Resurrectio is a cloud-based reentry case management platform designed for organizations serving people with criminal justice involvement. The platform provides case management, service coordination, outcome tracking, and Narrative Relational Intelligence (NRI) capabilities. Resurrectio operates on a multi-tenant architecture, ensuring each organization\'s data is logically separated and independently managed.',
  },
  {
    icon: Users,
    title: '3. Account Responsibilities',
    content:
      'Organizations are responsible for all activity conducted under their accounts, including the actions of individual team members. Account administrators control user permissions, access levels, and role assignments within their organization. You must maintain accurate and current contact information for your account. You are responsible for safeguarding login credentials and must notify us immediately of any unauthorized access.',
  },
  {
    icon: Database,
    title: '4. Data Ownership',
    content:
      'Your data belongs to your organization. Resurrectio does not claim ownership over any data you enter into the platform. We never sell, share, or mine tenant data for any purpose beyond providing the service. You may export all of your data at any time in standard formats. Upon termination, your data remains available for export as described in the Termination section below.',
  },
  {
    icon: ShieldCheck,
    title: '5. Acceptable Use',
    content:
      'You must not use Resurrectio to discriminate against, harass, or violate the rights of returning citizens or any other individuals. You must comply with all applicable laws and regulations, including but not limited to CJIS Security Policy, HIPAA, and 42 CFR Part 2 (substance use disorder record protections). You must not attempt to access, view, or modify data belonging to other tenant organizations. You must not reverse-engineer, decompile, or attempt to extract source code from the platform.',
  },
  {
    icon: Scale,
    title: '6. Privacy & Data Protection',
    content:
      'Our collection, use, and protection of personal information is governed by our Privacy Policy, available at /privacy. Resurrectio employs tenant-scoped data isolation with strict row-level security policies. All data is encrypted at rest (AES-256) and in transit (TLS 1.3). We are committed to protecting the privacy and dignity of the individuals whose information is managed through our platform.',
  },
  {
    icon: Brain,
    title: '7. NRI (Narrative Relational Intelligence)',
    content:
      'NRI is Resurrectio\'s intelligence layer that surfaces patterns, signals, and actionable insights within your organization\'s data. NRI suggests and surfaces signals — it never acts autonomously. All decisions are made by human users. NRI does not access data across tenant boundaries; all analysis is performed within your organization\'s data scope. All signals generated by NRI include supporting evidence and confidence metrics, enabling informed human judgment.',
  },
  {
    icon: Clock,
    title: '8. Service Level',
    content:
      'Resurrectio targets 99.9% platform uptime, measured monthly. Scheduled maintenance windows will be communicated to active administrators with advance notice. We maintain regular data backups to protect against data loss. In the event of unplanned downtime, we will provide timely status updates and work to restore service as quickly as possible.',
  },
  {
    icon: CreditCard,
    title: '9. Payment Terms',
    content:
      'Resurrectio uses capacity-based pricing — you pay based on the scale of your program, not per seat. Subscriptions are billed monthly. New organizations receive a 30-day free trial with full platform access. Subsidized access is available for qualifying nonprofit, faith-based, and community organizations serving returning citizens. Contact us for eligibility details.',
  },
  {
    icon: LogOut,
    title: '10. Termination',
    content:
      'Either party may terminate this agreement with 30 days written notice. Upon termination, your data will remain available for export for 90 days. After the 90-day export window, data may be scheduled for deletion. We will never delete your data without your explicit written request. If you wish to have your data deleted immediately upon termination, you may request this in writing.',
  },
  {
    icon: AlertTriangle,
    title: '11. Limitation of Liability',
    content:
      'To the maximum extent permitted by law, CROS LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the platform. Resurrectio is a tool designed to support human judgment in reentry case management. It is not a substitute for professional case management, legal advice, medical advice, or clinical assessment. Users are responsible for exercising professional judgment in all decisions affecting the individuals they serve.',
  },
  {
    icon: RefreshCw,
    title: '12. Changes to Terms',
    content:
      'We reserve the right to modify these Terms of Service. We will notify all active organizations at least 30 days before any material changes take effect. Continued use of the platform after changes take effect constitutes acceptance of the revised terms. Previous versions of these terms are available upon request.',
  },
  {
    icon: Mail,
    title: '13. Contact',
    content:
      'For questions about these Terms of Service, contact us at legal@resurrectio.app. For data protection inquiries, contact dpo@resurrectio.app.',
  },
];

export default function Terms() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-16">
      <header className="mb-12 text-center">
        <h1 className="font-serif text-4xl font-bold text-red-900 mb-3">
          Resurrectio Terms of Service
        </h1>
        <p className="text-red-950/50 text-sm">
          Effective: April 2026
        </p>
      </header>

      <div className="space-y-6">
        {sections.map((section) => {
          const Icon = section.icon;
          return (
            <Card key={section.title} className="border-red-100">
              <CardHeader className="pb-2">
                <div className="flex items-center gap-3">
                  <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-red-50 text-red-800">
                    <Icon className="h-5 w-5" />
                  </div>
                  <CardTitle className="font-serif text-lg text-red-900">
                    {section.title}
                  </CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-sm leading-relaxed text-red-950/70">
                  {section.content}
                </p>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <div className="mt-12 text-center text-xs text-red-950/40">
        <p>&copy; {new Date().getFullYear()} CROS LLC. All rights reserved.</p>
      </div>
    </div>
  );
}
